### ISSUE TITLE
lv2lint and sord_validate fail

### ISSUE THREAD

**Issue by dvzrv** [sjaehn/BSlizr#8] opened 2020-01-06 13:21 UTC
When packaging 1.2.4 for Arch Linux, I ran [lv2lint](https://open-music-kontrollers.ch/lv2/lv2lint/) and [sord_validate](https://lv2plug.in/pages/validating-lv2-data.html) on the resulting plugin, but both fail:

[bslizr-1.2.4-1-x86_64-check.log](https://github.com/sjaehn/BSlizr/files/4026145/bslizr-1.2.4-1-x86_64-check.log)

While `sord_validate` probably holds many false-positives, it would be nice, if the `lv2lint` errors would be fixed.
Thanks!

**Comment by sjaehn** [comment] 2020-01-06 15:40
Hi David, I can't reproduce your lv2lint log with the recent versions of lv2 (1.16) and lv2lint (actual master). I get only two warns: Linking (wontfix) and E-mail (wontfix).

`[WARN]  Class`: I think it's because my classification as a` lv2:DynamicsPlugin`. This is not that long in lv2 specifications.

`[FAIL]  Toolkit`: http://lv2plug.in/ns/extensions/ui#X11UI is valid since 1.2.4 (I think). I really don't know why you get a FAIL message. I'll ask Hanspeter.

`sord_validate` doesn't help as it ignores includes. To find a real error in the `sord_validate` output is like to find a needle in the haystack. lv2lint should show all relevant information.

I'm only wondering about the lilv_world* errors.

**Comment by ventosus** [comment] 2020-01-07 09:08
> I get only two warns: Linking (wontfix) and E-mail (wontfix).

I only get these two warnings, too.

    $ lv2lint -I ./BSlizr.lv2/ https://www.jahnichen.de/plugins/lv2/BSlizr
    lv2lint 0.2.0
    Copyright (c) 2016-2019 Hanspeter Portner (dev@open-music-kontrollers.ch)
    Released under Artistic License 2.0 by Open Music Kontrollers
    <https://www.jahnichen.de/plugins/lv2/BSlizr>
        [WARN]  Linking
                  binary links to C++ libraries: 
                    * libstdc++.so.6
                    * libgcc_s.so.1
                  seeAlso: <http://lv2plug.in/ns/lv2core#binary>
        [WARN]  Author Email
                  foaf:email not found
                  seeAlso: <http://lv2plug.in/ns/lv2core#project>

**Comment by ventosus** [comment] 2020-01-07 09:15
lv2_validate only shows 3 errors here.
    $ lv2_validate ./BSlizr.lv2/*.ttl
    error: Subject not in domain <http://usefulinc.com/ns/doap#Project>
           https://www.jahnichen.de/plugins/lv2/BSlizr
           http://usefulinc.com/ns/doap#maintainer
           http://www.jahnichen.de/sjaehn#me
    error: Use of undefined property
           https://www.jahnichen.de/plugins/lv2/BSlizr#gui
           http://lv2plug.in/ns/extensions/ui#requiredFeature
           http://lv2plug.in/ns/extensions/ui#makeResident
    error: Property <http://lv2plug.in/ns/extensions/ui#requiredFeature> has no label
           https://www.jahnichen.de/plugins/lv2/BSlizr#gui
           http://lv2plug.in/ns/extensions/ui#requiredFeature
           http://lv2plug.in/ns/extensions/ui#makeResident
    Found 3 errors among 98 files (checked 2273 restrictions)
I cannot find this here in the spec at all, where do you have that from ?
    http://lv2plug.in/ns/extensions/ui#makeResident

**Comment by ventosus** [comment] 2020-01-07 09:18
@dvzrv  A borked LV2 installation, or wrong LV2_PATH, maybe ?

btw, I'm on Parabola, so not much differences.

**Comment by ventosus** [comment] 2020-01-07 09:21
@sjaehn this fixes the first sord_validate error:

    diff --git a/BSlizr.ttl b/BSlizr.ttl
    index 460393a..80fde3d 100644
    --- a/BSlizr.ttl
    +++ b/BSlizr.ttl
    @@ -24,7 +24,7 @@
            ui:requiredFeature ui:makeResident .
 
     <https://www.jahnichen.de/plugins/lv2/BSlizr>
    -        a lv2:Plugin, lv2:DynamicsPlugin ;
    +        a lv2:Plugin, lv2:DynamicsPlugin, doap:Project ;
             doap:name "B.Slizr" ;
             rdfs:comment "LV2 audio effect plugin. This plugin slices stereo audio input signals with a     length up to 1 bar into up to 16 pieces. As result it may produce a step sequencer-like effect." ;
            doap:maintainer <http://www.jahnichen.de/sjaehn#me> ;

**Comment by ventosus** [comment] 2020-01-07 09:25
@sjaehn maybe you meant this here ?

    http://lv2plug.in/ns/extensions/ui/#makeSONameResident

As it is marked as DEPRECATED, you can as well remove it and your plugin will pass with flying colors.

**Comment by sjaehn** [comment] 2020-01-07 10:39
Thank you, venosus. No idea where from where I got ui:makeResident. All fixed in d127534ac41ad09acc3c2c0720b692a1c4b7b5ba .

**Closed** 2020-01-07 10:40 UTC
